zookeeper:
  image: jplock/zookeeper:3.4.5
  hostname: zookeeper

mesosmaster:
  image: djosborne/mesos-modules-dev:0.26.0-rc4
  hostname: mesosmaster
  command: /mesos/build/bin/mesos-master.sh
  environment:
    - MESOS_QUORUM=1
    - MESOS_WORK_DIR=/var/lib/mesos
    - MESOS_LOG_DIR=/var/log
    - MESOS_ZK=zk://zookeeper:2181/mesos
    - MESOS_ROLES=public
  volumes:
    - /var/log/mesos:/var/log/mesos
    - ./framework/:/framework
  ports:
    - "5050:5050"
  links:
    - zookeeper

proxy:
  image: svendowideit/ambassador
  environment:
    - COLLECTOR_PORT_9001_TCP=tcp://collect-star-iso.marathon.mesos:9001
  dns:
   - 192.168.255.254
  ports:
    - "9001:9001"

slavepublic:
  build: .
  privileged: true
  links:
    - mesosmaster
    - zookeeper
    - etcd
  volumes:
    - /var/log/mesos:/var/log/mesos
    - ./framework:/framework
  environment:
    - MESOS_MASTER=zk://zookeeper:2181/mesos
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_CONTAINERIZERS=mesos
    - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
    - MESOS_LOG_DIR=/var/log
    - MESOS_RESOURCES=ports:[9000-31100]
    - MESOS_DEFAULT_ROLE=public
    - MESOS_MODULES=file:///calico/modules.json
    - MESOS_ISOLATION=com_mesosphere_mesos_NetworkIsolator
    - MESOS_HOOKS=com_mesosphere_mesos_NetworkHook
    - ETCD_AUTHORITY=etcd:4001
  dns:
   - 192.168.255.254

slave:
  build: .
  privileged: true
  links:
    - mesosmaster
    - zookeeper
    - etcd
  volumes:
    - /var/log/mesos:/var/log/mesos
    - ./framework:/framework
  environment:
    - MESOS_MASTER=zk://zookeeper:2181/mesos
    - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
    - MESOS_CONTAINERIZERS=mesos
    - MESOS_ISOLATOR=cgroups/cpu,cgroups/mem
    - MESOS_LOG_DIR=/var/log
    - MESOS_RESOURCES=ports(*):[30000-31100]
    - MESOS_MODULES=file:///calico/modules.json
    - MESOS_ISOLATION=com_mesosphere_mesos_NetworkIsolator
    - MESOS_HOOKS=com_mesosphere_mesos_NetworkHook
    - ETCD_AUTHORITY=etcd:4001
  dns:
   - 192.168.255.254

marathon:
  image: mesosphere/marathon-test:c47428883f10
  environment:
    - MARATHON_MASTER=zk://zookeeper:2181/mesos
    - MARATHON_ZK=zk://zookeeper:2181/marathon
    - MARATHON_MAX_TASKS_PER_OFFER=32
    - MARATHON_MESOS_ROLE=public
  command: "--default_accepted_resource_roles *"
  ports:
    - "8080:8080"
  links:
    - mesosmaster
    - zookeeper

etcd:
  image: spikecurtis/single-etcd:2.0.9
